### ISSUE TITLE
Invalid capabilities names

### ISSUE THREAD

**Issue by mudrd8mz** [JotaDF/block_game#1]
The block does not define the standard capability `block/game:addinstance`

There is a capability `block/block_game:addinstance` that I believe was supposed to server that purpose.

Other capabilities `moodle/block_game:edit` and `block/block_game:myaddinstance` also do not follow the standard way of naming caps. Please refer to other plugins for examples.

**Comment by JotaDF** [comment]
To fix this problem I will need to change many files, I will take advantage and change to another repository with the correct name moodle-blockgame. This change may affect users testing the plugin today.

**Comment by mudrd8mz** [comment]
> change to another repository with the correct name moodle-blockgame

Please note, the expected repository name is `moodle-block_game` and the rename is not an issue on github. They even make it transparent so that the old URL still continues to work for a while.

**Comment by JotaDF** [comment]
I created another repository with the correct name, because that repository has already been released! Follow the link below!
https://github.com/JotaDF/moodle-blockgame
